# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=255, verbose_name='书名')),
                ('a_info', models.CharField(max_length=300, verbose_name='简介')),
                ('a_content', models.TextField(verbose_name='内容')),
                ('a_img', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='封面')),
                ('a_addtime', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('a_updatetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-a_addtime'],
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255, verbose_name='标签名')),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.Tag', verbose_name='标签名'),
        ),
    ]
